name: Build and publish docker images
on:
  push:
    branches: ['main']
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - id: repository
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
          context: node/
          push: true
          tags: ${{ steps.repository.outputs.lowercase }}/node:${{ github.sha }}
